services:
  aws_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.aws.frontend.prod
    container_name: aws_frontend
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3030:3030"
    restart: unless-stopped