services:
  aws_backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile.aws.backend.prod
    container_name: aws_backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    networks:
      - net_hci

  aws_frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile.aws.frontend.prod
    container_name: aws_frontend
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3030:3030"
    networks:
      - net_hci
    restart: unless-stopped

  aws_mongo_db:
    platform: linux/amd64
    build:
      context: ./mongo_db
      dockerfile: Dockerfile.aws.mongo.prod
    container_name: aws_mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - net_hci
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g
        reservations:
          cpus: '1.0'
          memory: 2g

  aws_mongo_express:
    platform: linux/amd64
    build:
      context: ./mongo_express
      dockerfile: Dockerfile.aws.mongoexpress.prod
    container_name: aws_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - net_hci
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
        reservations:
          cpus: '0.25'
          memory: 256m

networks:
  net_hci:
    driver: bridge